name: DO Deploy

on: 
  push:
    branches: [ main ]
    
jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@main
      
      - run: docker-compose down
      - run: docker-compose up -d
